# Generated by Django 4.0.3 on 2022-07-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_amount_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIKIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
