# Generated by Django 4.0.3 on 2022-07-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_imageikio_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageIKIO',
        ),
    ]
